### ISSUE TITLE
GTSPP config for WOA test

### ISSUE THREAD

**Issue by s-good** [castelao/CoTeDe#17]
Hi @castelao. Thanks for making this software available! I've been working through all the tests you have implemented and I noticed that the WOA_normbias config in gtspp.json includes the variable 't_an', which I think should be 't_mn'. Also, I'm not sure about this, but I think that the 'at_sea' test in the same file (and some of the other config files) may not work unless it is called 'location_at_sea'?

**Comment by castelao** [comment]
Thank you so much @s-good! You were right, I addressed both issues. I'm sorry about that.
