### ISSUE TITLE
flag setting in location_at_sea.py

### ISSUE THREAD

**Issue by s-good** [castelao/CoTeDe#18]
Hi @castelao, sorry to raise another issue but I found that my code was failing if a profile location was on land. I think it might be because 'flag' is not set before it is used in location_at_sea.py. If I set flag = 3 it runs through as expected.

**Comment by castelao** [comment]
@s-good thanks for finding that. I have no clue where did that 'flag' came from. I fixed that and upgraded the package.

I included some tests for that at CoTeDe. It should be working fine now, otherwise, please re-open this issue. Thank you very much!
