### ISSUE TITLE
Threshold for tukey53H_norm in cotede configuration

### ISSUE THREAD

**Issue by s-good** [castelao/CoTeDe#19]
Hi again @castelao, I just wanted to check what threshold should be for the tukey53H_norm test in the cotede.json configuration? At the moment it looks like it is picking up the value of the threshold from the last test run (2). Is this the correct value to use?

**Comment by castelao** [comment]
The parameter k should be the threshold, with default value of 1.5. Sorry about that.

Thank you so much @s-good!
