### ISSUE TITLE
Fuzzylogic and Morello2014 tests

### ISSUE THREAD

**Issue by s-good** [castelao/CoTeDe#28]
Hi @castelao, I noticed you have two config files for fuzzy logic tests - fuzzylogic.json and morello2014.json. The settings look very similar in both. For AutoQC should I consider these as separate tests or would you say that they are too similar to bother?

**Comment by castelao** [comment]
Hi @s-good, sorry for the delay. Yes, the inputs are similar, but the tests are different. It's probably worth to run both.

**Comment by s-good** [comment]
Thanks @castelao!
