### ISSUE TITLE
numpy version

### ISSUE THREAD

**Issue by BillMills** [castelao/CoTeDe#35]
`print(numpy.fmin(numpy.zeros(1), numpy.ma.masked) is numpy.ma.masked)`

evaluates to true in numpy 1.11 and 1.12, but false in 1.13. So what? This changes how some of cotede's fuzzy logic gets evaluated at https://github.com/castelao/CoTeDe/blob/master/cotede/fuzzy/fuzzy_core.py#L139-L140 - numpy 1.13+ will fail to bail out on that if clause.

If you agree, you may consider pinning `numpy>=1.11.1,<=1.12.1`.

**Comment by castelao** [comment]
Thanks @BillMills . I'm sorry for the slow response.

This bug was [already fixed some time ago](https://github.com/castelao/CoTeDe/commit/32616197cc680a1866a7c156fa65b6ed05685529). Please upgrade to the latest public version on pypi and let me know if that still doesn't work.

**Comment by castelao** [comment]
[already fixed some time ago](url)
