### ISSUE TITLE
Problems following basic usage - logger issue

### ISSUE THREAD

**Issue by shaunwbell** [castelao/CoTeDe#36]
Wanted to try out your algorithms and see if they can be applied to our data... installed the package per instructions and got the following error

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-43-02ba7dda9ecb> in <module>
----> 1 pqc = fProfileQC('dPIRX003.cnv')

~/anaconda2/envs/cotede/lib/python3.7/site-packages/cotede/qc.py in __init__(self, inputfile, cfg, saveauxiliary, verbose, logger)
    467             # Not the best way, but will work for now. I should pass
    468             #   the reference for the logger being used.
--> 469             input = cnv.fCNV(inputfile, logger=None)
    470         except CNVError as e:
    471             #self.attributes['filename'] = basename(inputfile)

TypeError: __init__() got an unexpected keyword argument 'logger'
```

Any guidance? I've tried it on python 3.7, and 2.7 with the same error.
Thanks

**Comment by castelao** [comment]
Hi @shaunwbell , I'm really sorry for haven't been able to address this before. I was in the middle of a major refactoring and moving things around.

The idea now is that CoTeDe is moving into a flexible library that only cares about the QC and leaves the data format handling for other packages. By doing that I'm extending to other data realms. If you're interested in QCing CTD or TSG, please check the package [pySeabird](https://github.com/castelao/seabird/blob/dev/docs/notebooks/QualityControl.ipynb), which first parse the CTD data and then apply the QC tests using CoTeDe. I'll make soon more notebooks to illustrate the process better.

Please, let me know your questions and thanks for the interest.

**Comment by shaunwbell** [comment]
sounds good @castelao , I will try the package out and get back to you
