### ISSUE TITLE
Add conda-forge packages for CoTeDe and oceansdb

### ISSUE THREAD

**Issue by jessicaaustin** [castelao/CoTeDe#39]
Our team uses conda and conda-forge to manage dependencies for our python projects. Looks like neither CoTeDe nor oceansdb are in conda-forge. Looks like [GSW is in there](https://github.com/conda-forge/gsw-feedstock).

**Comment by castelao** [comment]
https://github.com/conda-forge/oceansdb-feedstock

https://github.com/conda-forge/cotede-feedstock
