### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by jessicaaustin** [castelao/CoTeDe#41]
I might be missing something, but I don't see docs for the API at https://cotede.readthedocs.io/en/latest/readme.html

Looks like the code as docstrings for most classes and test methods, so this is probably just a matter of configuring sphinx to produce the docs.

**Comment by castelao** [comment]
@jessicaaustin , thanks for raising this issue. I updated the documentation (https://cotede.readthedocs.io) to include the main resources that a new user should know. I'll soon finish cleaning the code of this package, and then I'll be able to use the automatic mode for a more extensive documentation coverage.
