### ISSUE TITLE
add alternative methods for calculating salinity

### ISSUE THREAD

**Issue by evanleeturner** [castelao/CoTeDe#43]
My packages (eg. https://github.com/evanleeturner/sonde3) use the PyPi seawater package to calculate salinity: https://pypi.org/project/seawater/

Since calculating salinity may be different among groups and also affects your written QAPP/QAQC having the ability to apply alternative methods for seawater conversion instead of the GSW package using the Thermodynamic Equation of Seawater 2010 (TEOS-10) method or creating specific forks to the CoTeDe package would be an excellent feature of this codebase!

**Comment by castelao** [comment]
Nice! Thanks. I agree that it can cause some differnce, but I have to think about it. It might not be the job of CoTeDe to decide which procedure to use to obtain the salinity, but restrict on evaluating the data that is given. I believe that I currently use GSW only to estimate the density when it's not available, to identify density inversions.

CoTeDe was originally a full CTD processing tool, from parsing different formats, QC, and exporting netCDFs, but as it grew too large, I split that in multiple packages. For instance, now [pySeabird](https://github.com/castelao/seabird) deals with some formats of CTD, and calls CoTeDe to QC the data.

**Comment by castelao** [comment]
Hi @evanleeturner , thanks for your suggestion. This is indeed relevant for comparing datasets, or evaluating long time series, but, as I mentioned before, I don't think it is the job for CoTeDe. My vision for CoTeDe is to be used by other packages for specific tasks. While CoTeDe focus on QC, these overarching packages would deal with problems like you raised - a uniform data processing - and deliver what is to be quality controlled to CoTeDe. If you plan to develop that for your internal project, let me know if I can give you suggestions on how to integrate it. Cheers,
